// app/layout.tsx
import type { Metadata, MetadataRoute } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { AuthProvider } from "@/context/auth-context";
import { Toaster } from "sonner";
import { ApiStatus } from "@/components/api-status";
import { GoogleOAuthProvider } from '@react-oauth/google'

const spaceMono = localFont({
  src: [
    {
      path: "./fonts/SpaceMono-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/SpaceMono-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-space-mono",
  display: "swap",
});

export const metadata: Metadata = {
  title: "AI Fitness & Nutrition Planner",
  description: "Your personalized AI-powered guide to fitness and nutrition.",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 const googleClientId = process.env.NEXT_PUBLIC_GOOGLE_AUTH_CLIENT_ID;

 if (!googleClientId) {
   console.error(
     "FATAL: NEXT_PUBLIC_GOOGLE_AUTH_CLIENT_ID is not defined in .env.local"
   );
   // You might want to render an error page here
   return (
     <html lang="en" suppressHydrationWarning>
       <body>
         <h1 style={{ color: "red", padding: "2rem" }}>
           Error: Google Client ID is not configured.
         </h1>
       </body>
     </html>
   );
 }
  
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${spaceMono.className} ${spaceMono.variable} antialiased`}
      >
        <GoogleOAuthProvider clientId={googleClientId as string}>
        <ApiStatus />

        <AuthProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            disableTransitionOnChange
            >
            {children}
          </ThemeProvider>
        </AuthProvider>
        <Toaster
          visibleToasts={5}
          position={"top-right"}
          closeButton
          toastOptions={{
            unstyled: true,
            classNames: {
              toast:
              "glass w-100 min-h-20 p-4 rounded-lg flex items-center justify-center gap-2",
              closeButton: "absolute top-0.5 right-0.5 rounded-full",
            },
          }}
          />
          </GoogleOAuthProvider>
      </body>
    </html>
  );
}
/////////////////////old code//////////////////////
// import type { Metadata } from "next";
// import localFont from "next/font/local";
// import "./globals.css";
// import { ThemeProvider } from "@/components/theme-provider";
// import { AnimatedBackground } from "@/components/animated-background";
// import { AuthProvider } from "@/context/auth-context";
// import { Toaster } from "sonner";
// import { ApiStatus } from "@/components/api-status";

// const spaceMono = localFont({
//   src: [
//     {
//       path: "./fonts/SpaceMono-Regular.ttf",
//       weight: "400",
//       style: "normal",
//     },
//     {
//       path: "./fonts/SpaceMono-Bold.ttf",
//       weight: "700",
//       style: "normal",
//     },
//   ],
//   variable: "--font-space-mono",
//   display: "swap",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {

//   return (
//     <html lang="en" suppressHydrationWarning>
//       <body
//         className={`${spaceMono.className} ${spaceMono.variable} antialiased`}
//       >
//         <ApiStatus />
//         {/* <AnimatedBackground /> */}
//         <AuthProvider>

//         <ThemeProvider
//           attribute="class"
//           defaultTheme="dark"
//           disableTransitionOnChange
//           >
//           {children}
//         </ThemeProvider>
//           </AuthProvider>
//           <Toaster visibleToasts={5} position={"top-right"}
//           // richColors
//           closeButton
//           toastOptions={{
//             unstyled: true,
//             classNames: {
//               toast: "glass w-100 min-h-20 p-4 rounded-lg flex items-center justify-center gap-2",
//               closeButton: "absolute top-0.5 right-0.5 rounded-full"
//             }
//           }}
//           />
//       </body>
//     </html>
//   );
// }
